backend:
  name: git-gateway
  branch: main

media_folder: "frontend/public/images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - file: "frontend/public/content/gallery.json"
        label: "Gallery Images"
        name: "gallery"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Category", name: "category", widget: "string", required: false }
              - { label: "Image", name: "url", widget: "image" }